import '@repo/ui/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Providers from './providers';
import Header from '../components/header';

export const metadata: Metadata = {
  title: 'Decentralized Fiverr',
  description: 'Generated by create turbo',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body suppressHydrationWarning className={inter.className}>
        <Providers>
          <Header />
          <div className='max-w-7xl mx-auto'>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
